"""Centralized system ID generation utilities.

Persistent IDs are generated by system code and must not be invented by the LLM.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from uuid import uuid4

from src.schemas.case_structurer.common import (
    AmbiguityID,
    CaseID,
    EventID,
    InputID,
    ItemID,
    SectionID,
    SpanID,
    StageID,
)

_PREFIX_PATTERN = re.compile(r"^[a-z0-9_]+$")


def generate_id(prefix: str) -> str:
    """Generate a persistent ID in the format {prefix}_{YYYYMMDD}_{short_uuid}."""
    if not isinstance(prefix, str) or not prefix:
        raise ValueError("prefix must be a non-empty string.")

    if _PREFIX_PATTERN.fullmatch(prefix) is None:
        raise ValueError(
            "prefix may contain only lowercase letters, digits, and underscores."
        )

    date_part = datetime.now(timezone.utc).strftime("%Y%m%d")
    short_uuid = uuid4().hex[:8]
    return f"{prefix}_{date_part}_{short_uuid}"


def generate_case_id() -> CaseID:
    return CaseID(generate_id("case"))


def generate_input_id() -> InputID:
    return InputID(generate_id("input"))


def generate_stage_id() -> StageID:
    return StageID(generate_id("stage"))


def generate_span_id() -> SpanID:
    return SpanID(generate_id("span"))


def generate_source_span_id() -> SpanID:
    return generate_span_id()


def generate_section_id() -> SectionID:
    return SectionID(generate_id("section"))


def generate_clinical_section_id() -> SectionID:
    return generate_section_id()


def generate_item_id() -> ItemID:
    return ItemID(generate_id("item"))


def generate_structured_item_id() -> ItemID:
    return generate_item_id()


def generate_event_id() -> EventID:
    return EventID(generate_id("event"))


def generate_timeline_event_id() -> EventID:
    return generate_event_id()


def generate_ambiguity_id() -> AmbiguityID:
    return AmbiguityID(generate_id("ambiguity"))
