from __future__ import annotations

from collections.abc import Iterable
from enum import StrEnum

from src.agents.evidence_atomizer.modules.atomization_candidate_builder import (
    AtomizationCandidate,
)
from src.agents.evidence_atomizer.modules.coverage_units import CoverageUnit


def format_atomization_candidates(candidates: list[AtomizationCandidate]) -> str:
    if not candidates:
        return "(none)"

    lines: list[str] = []
    for candidate in candidates:
        span_text = "; ".join(
            f"{span.get('span_id')}: {_compact_text(str(span.get('quoted_text', '')))}"
            for span in candidate.source_spans
        )
        lines.append(
            " | ".join(
                [
                    f"item_id={candidate.item_id}",
                    f"item_type={candidate.item_type}",
                    f"label={_compact_text(candidate.label)}",
                    f"temporality={candidate.temporality}",
                    f"certainty={candidate.certainty}",
                    f"negation={candidate.negation}",
                    f"attributes={_format_attributes(candidate)}",
                    f"section_id={candidate.section_id}",
                    f"section_type={candidate.section_type}",
                    f"section_title={candidate.section_title}",
                    f"source_spans=[{span_text}]",
                ]
            )
        )
    return "\n".join(f"- {line}" for line in lines)


def format_coverage_units(coverage_units: list[CoverageUnit]) -> str:
    if not coverage_units:
        return "(none)"

    lines: list[str] = []
    for unit in coverage_units:
        lines.append(
            " | ".join(
                [
                    f"coverage_unit_id={unit.unit_id}",
                    f"source_item_id={unit.source_item_id}",
                    f"source_attribute_ids={unit.source_attribute_ids}",
                    f"source_span_ids={unit.source_span_ids}",
                    f"surface_text={_compact_text(unit.surface_text)}",
                    f"clinical_object={_compact_text(unit.clinical_object)}",
                    f"status_or_direction={unit.status_or_direction}",
                    f"modifier_texts={unit.modifier_texts}",
                    f"assertion_status={unit.assertion_status}",
                    f"assertion_cue_text={unit.assertion_cue_text}",
                    f"assertion_scope_text={_compact_text(str(unit.assertion_scope_text or ''))}",
                    f"clinical_object_type={unit.clinical_object_type}",
                    f"clinical_object_assertion_id={unit.clinical_object_assertion_id}",
                    f"source_frame_node_ids={unit.source_frame_node_ids}",
                    f"context_frame_node_ids={unit.context_frame_node_ids}",
                    f"parent_frame_node_id={unit.parent_frame_node_id}",
                    f"relation_to_parent={unit.relation_to_parent}",
                    f"inherited_context_text={_compact_text(str(unit.inherited_context_text or ''))}",
                    f"local_content_text={_compact_text(str(unit.local_content_text or ''))}",
                    f"atomization_policy={unit.atomization_policy}",
                    f"certainty={unit.certainty}",
                    f"temporality={unit.temporality}",
                    f"split_basis={unit.split_basis}",
                    f"required={unit.required}",
                ]
            )
        )
    return "\n".join(f"- {line}" for line in lines)


def format_atomization_boundary() -> str:
    return "\n".join(
        [
            "- Evidence Atomizer receives validated StructuredClinicalItem material.",
            "- ClinicalAttribute summaries are target-grounded modifier relations, not independent facts.",
            "- It creates minimal source-grounded evidence atom drafts.",
            "- It preserves source item ids, source attribute ids, and source span ids.",
            "- It does not decide disease support, refutation, diagnosis, or action.",
            "- It defers ambiguous or non-clinical material instead of guessing.",
            "- Persistent ids are generated by code after the LLM response.",
        ]
    )


def format_forbidden_downstream_objects() -> str:
    forbidden = [
        "diagnosis selection",
        "diagnostic hypothesis",
        "support/refute relationship",
        "treatment recommendation",
        "ActionPlan",
        "HypothesisState",
        "Conflict",
        "UpdateTrace",
        "ArbitrationResult",
        "SafetyGateResult",
        "StateWriter output",
    ]
    return "\n".join(f"- {item}" for item in forbidden)


def format_enum_options(values: Iterable[str]) -> str:
    value_list = list(values)
    if not value_list:
        return "(none)"
    return "\n".join(f"- {value}" for value in value_list)


def _compact_text(text: str, limit: int = 120) -> str:
    compacted = " ".join(text.split())
    if len(compacted) <= limit:
        return compacted
    return f"{compacted[: limit - 3]}..."


def _format_attributes(candidate: AtomizationCandidate) -> str:
    if not candidate.attributes:
        return "[]"
    return "[" + "; ".join(
        (
            f"{attribute.attribute_id}:"
            f"role={attribute.attribute_role},"
            f"scope={attribute.attribute_scope},"
            f"span={_compact_text(attribute.span_text, limit=40)},"
            f"applies_to={_compact_text(str(attribute.applies_to_text or ''), limit=50)},"
            f"context={_compact_text(attribute.context_text, limit=70)}"
        )
        for attribute in candidate.attributes
    ) + "]"


def _enum_values(enum_cls: type[StrEnum]) -> list[str]:
    return [item.value for item in enum_cls]
