from __future__ import annotations

from collections.abc import Iterable
from enum import StrEnum

from src.agents.evidence_atomizer.modules.atomization_candidate_builder import (
    AtomizationCandidate,
)


def format_atomization_candidates(candidates: list[AtomizationCandidate]) -> str:
    if not candidates:
        return "(none)"

    lines: list[str] = []
    for candidate in candidates:
        span_text = "; ".join(
            f"{span.get('span_id')}: {_compact_text(str(span.get('quoted_text', '')))}"
            for span in candidate.source_spans
        )
        lines.append(
            " | ".join(
                [
                    f"item_id={candidate.item_id}",
                    f"item_type={candidate.item_type}",
                    f"label={_compact_text(candidate.label)}",
                    f"value={candidate.value}",
                    f"unit={candidate.unit}",
                    f"body_site={candidate.body_site}",
                    f"temporality={candidate.temporality}",
                    f"time_text={candidate.time_text}",
                    f"certainty={candidate.certainty}",
                    f"negation={candidate.negation}",
                    f"section_id={candidate.section_id}",
                    f"section_type={candidate.section_type}",
                    f"section_title={candidate.section_title}",
                    f"source_spans=[{span_text}]",
                ]
            )
        )
    return "\n".join(f"- {line}" for line in lines)


def format_atomization_boundary() -> str:
    return "\n".join(
        [
            "- Evidence Atomizer receives validated StructuredClinicalItem material.",
            "- It creates minimal source-grounded evidence atom drafts.",
            "- It preserves source item ids and source span ids.",
            "- It does not decide disease support, refutation, diagnosis, or action.",
            "- It defers ambiguous or non-clinical material instead of guessing.",
            "- Persistent ids are generated by code after the LLM response.",
        ]
    )


def format_forbidden_downstream_objects() -> str:
    forbidden = [
        "diagnosis selection",
        "diagnostic hypothesis",
        "support/refute relationship",
        "treatment recommendation",
        "ActionPlan",
        "HypothesisState",
        "Conflict",
        "UpdateTrace",
        "ArbitrationResult",
        "SafetyGateResult",
        "StateWriter output",
    ]
    return "\n".join(f"- {item}" for item in forbidden)


def format_enum_options(values: Iterable[str]) -> str:
    value_list = list(values)
    if not value_list:
        return "(none)"
    return "\n".join(f"- {value}" for value in value_list)


def _compact_text(text: str, limit: int = 120) -> str:
    compacted = " ".join(text.split())
    if len(compacted) <= limit:
        return compacted
    return f"{compacted[: limit - 3]}..."


def _enum_values(enum_cls: type[StrEnum]) -> list[str]:
    return [item.value for item in enum_cls]
